echo "                     "
echo "                     "
ps -ef | grep competition-1.0-SNAPSHOT.jar  | grep -v grep 
echo "                     "
echo "                     "
echo "                     "
echo "                     "
echo "Killing now....."
echo "                     "
echo "                     "
echo "                     "
ps -ef | grep competition-1.0-SNAPSHOT.jar  | grep -v grep | awk '{print $2}' | xargs kill -15
echo "                     "
echo "                     "
echo "                     "
